name: Release

on:
  release:
    types: [published]

permissions:
  contents: write
  
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-dev --optimize-autoloader --ignore-platform-req=ext-posix --ignore-platform-req=ext-fileinfo
      # Note: We ignore posix and fileinfo requirements because:
      # - POSIX is not available on Windows
      # - CLI automatically falls back to individual commands when menu package is unavailable
      # - This ensures cross-platform compatibility

    - name: Get release version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build PHAR using Box
      run: |
        chmod +x ./vendor/laravel-zero/framework/bin/box
        ./vendor/laravel-zero/framework/bin/box compile

    - name: Create platform-specific builds
      run: |
        mkdir -p builds
        cp chargily.phar builds/chargily-linux
        cp chargily.phar builds/chargily-macos
        cp chargily.phar builds/chargily-windows.phar
        chmod +x builds/chargily-linux builds/chargily-macos

    - name: Create checksums
      run: |
        cd builds
        sha256sum chargily-linux chargily-macos chargily-windows.phar > checksums.sha256
        md5sum chargily-linux chargily-macos chargily-windows.phar > checksums.md5

    - name: Upload all release assets
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          builds/chargily-linux
          builds/chargily-macos
          builds/chargily-windows.phar
          builds/checksums.sha256
          builds/checksums.md5