name: Release

on:
  release:
    types: [published]

permissions:
  contents: write
  
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv

    - name: Get release version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    # Build Linux/macOS PHAR (with interactive menus)
    - name: Install dependencies for Linux/macOS
      run: composer install --prefer-dist --no-interaction --no-dev --optimize-autoloader

    - name: Build Linux/macOS PHAR
      run: |
        chmod +x ./vendor/laravel-zero/framework/bin/box
        ./vendor/laravel-zero/framework/bin/box compile
        mkdir -p builds
        cp chargily.phar builds/chargily-linux
        cp chargily.phar builds/chargily-macos
        chmod +x builds/chargily-linux builds/chargily-macos

    # Build Windows PHAR (without interactive menus)
    - name: Install dependencies for Windows
      run: |
        cp composer-windows.json composer.json
        composer install --prefer-dist --no-interaction --no-dev --optimize-autoloader

    - name: Build Windows PHAR  
      run: |
        ./vendor/laravel-zero/framework/bin/box compile
        cp chargily.phar builds/chargily-windows.phar

    # Restore original composer.json
    - name: Restore original composer.json
      run: git checkout -- composer.json

    - name: Create checksums
      run: |
        cd builds
        sha256sum chargily-linux chargily-macos chargily-windows.phar > checksums.sha256
        md5sum chargily-linux chargily-macos chargily-windows.phar > checksums.md5

    - name: Upload all release assets
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          builds/chargily-linux
          builds/chargily-macos
          builds/chargily-windows.phar
          builds/checksums.sha256
          builds/checksums.md5